In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Numpy

In [3]:
# a ~ b 구간만큼 array 생성
# c는 step
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [5]:
# a ~ b 구간을 c 만큼 나눈 array 생성
np.linspace(0, 100, 5, dtype=int)

array([  0,  25,  50,  75, 100])

In [6]:
# [a, b] 차원 만큼 random으로 채워진 array 생성
np.random.random([10, 3])

array([[0.34517424, 0.49476687, 0.89435696],
       [0.82324692, 0.0941569 , 0.52259373],
       [0.80103879, 0.48130936, 0.8999273 ],
       [0.70644837, 0.18863635, 0.7916967 ],
       [0.49075066, 0.22452528, 0.54332666],
       [0.1469197 , 0.29393614, 0.2724201 ],
       [0.22720586, 0.62462941, 0.29924542],
       [0.48124074, 0.92954402, 0.31134705],
       [0.89894857, 0.07837479, 0.75568723],
       [0.98427714, 0.04575574, 0.06184319]])

In [10]:
# np array의 mean 메서드는 axis=0, 1 을 지정 가능. 0은 열 단위, 1은 행 단위 연산
X = np.random.random([10, 3])
X.mean(axis=0)

array([0.46382926, 0.5983775 , 0.61475562])

In [12]:
# a 범위 안의 정수를 b 사이즈만큼 생성
arr1 = np.random.randint(10, size=(2, 3))
arr1

array([[8, 3, 9],
       [3, 1, 1]])

In [13]:
# 지정한 차원만큼 빈 array 생성 
np.ndarray([1, 2, 3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
# 파이썬 리스트끼리 concatenate() 수행할 경우
# list1 + list2 (일반 리스트의 + 연산 결과) 가 담긴 array 반환
list1 = [1, 2, 3]
list2 = [4, 5, 6]

print(list1 + list2)
np.concatenate([list1, list2])

[1, 2, 3, 4, 5, 6]


array([1, 2, 3, 4, 5, 6])

In [19]:
# 파이썬 리스트를 넘파이 어레이로 변환
np.array(list1)

array([1, 2, 3])

In [20]:
# 넘파이 어레이 간의 + 연산
np.array(list1) + np.array(list2)

array([5, 7, 9])

- 역수 :
    - 임의의 수  x에 대해서 곱했을 때 1이 되게 하는 수

- 역행렬 :
    - 임의의 행렬 x에 대해서 곱했을 때 항등행렬이 되게 하는 행렬


In [22]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[10, 20],
              [30, 40]])

C = A + B

print(C)

[[11 22]
 [33 44]]


In [23]:
# 역행렬 ( linear_algorithm )
# pinv는 역행렬이 구해지지 않는 행렬에 대해서
# 유사 역행렬를 구하는 함수
# A가 정방행렬이 아니라면 pinv를 사용

print(np.linalg.inv(A))
print(np.linalg.pinv(A))

# 행렬곱
D = np.matmul(A, B)
print(D)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 70 100]
 [150 220]]


In [24]:
x = np.array([[10], [20], [30], [40]])
# 행렬 x에 대해서, y 절편을 구하기 위해 각 차원에 요소로 1씩 추가해줌

A = np.array([[10, 1],  [20,1 ], [30,1], [40, 1]])
y = np.array([[71],  [45], [24], [8]])

W = np.matmul(np.linalg.pinv(A), y)
# 위 처럼 각 차원에 1씩 추가된 A의 역행렬과 y를 곱하면
# x 1단위 당, y의 증가량이 나옴
# 즉 가중치와 절편을 구할 수 있음.
# 행렬 A를 풀어쓰자면 10x+1, 20x+1, 30x+1, 40x+1 이기 때문.
# W[0]이 상수항(b)가 되고, W[1]이 가중치(w)가 됨.

print(f"{W[1]/W[0]}초 후 무게가 0이 됨")


# W는 linear_regression에서 coefficiency 라고 함. coef.
# W = 계수 = 기울기 = 가중치(weight) = 독립변수 수만큼 존재
# b = 편향 = y절편 = bias(b) = 상수항

[-42.61904762]초 후 무게가 0이 됨


- sklearn의 선형회귀
    - x의 역행렬을 구한 다음, y와 곱하는 과정을 간편화
    - model.fit(x, y) -> model.predict(x_pred)
    - model.coef_ : 기울기 혹은 가중치(w)와 같음
    - model.intercept_ : 절편(b)과 같음

- 모델 평가 지수
    - MAE (Mean Absolute Error) : 평균 절대 오차
    - MSE (Mean Square Error) : 평균 제곱 오차
    - RMSE (Root Mean Square Error) : 평균 제곱근 오차
    
- MAE는 값의 범위를 줄이는 데에 더 유용함

- p : predict 값 (예측값)
- y : 실제값
- abs(p-y) : 절대 오차
- mean(abs(p-y)) : 평균 절대 오차
- mean(abs(p-y)\*\*2) : 평균 제곱 오차
- sqrt(mean(abs(p-y)\*\*2) : 평균 제곱근 오차




### 택시 요금 비교

- 1, 2, 3, 4 km
- A 회사 : 5000, 7000, 8400, 10500
- B 회사 : 3100, 5400, 7900, 10900
- 9km갈 때 어떤 회사가 더 좋을까?
1. 각 회사별로 택시 요금을 모델링하여 비교하세요
2. 두 회사의 비용 차이가 0이 되는 거리를 도출하세요

In [30]:
model_A = LinearRegression()
model_B = LinearRegression()

x = np.array([[1], [2], [3], [4]])
y_a = np.array([5000, 7000, 8400, 10500])
y_b = np.array([3100, 5400, 7900, 10900])

model_A.fit(x, y_a)
model_B.fit(x, y_b)

pred_a = model_A.predict([[9]])
pred_b = model_B.predict([[9]])

print('a회사 9km 예상 요금 :', pred_a)
print('b회사 9km 예상 요금 :', pred_b)

print('a_W :', model_A.coef_)
print('a_b :', model_A.intercept_)

print('b_W :', model_B.coef_)
print('b_b :', model_B.intercept_)

a회사 9km 예상 요금 : [19360.]
b회사 9km 예상 요금 : [23660.]
a_W : [1790.]
a_b : 3249.999999999999
b_W : [2590.]
b_b : 349.9999999999991


In [32]:
# 위에서 도출한 각 모델의 w, b값에 대한 정의를 통해
# 두 값이 서로 0이 되는 지점을 계산할 수 있음

point = (3250 - 350) / (2590 - 1790)
print('a-b간 pred가 같아지는 거리:', point)
# 1790x + 3250 = 2590x + 350 되는 지점을 도출하기 위해 식 변환
# (a_b - b_b) / (b_w - a_w)

a-b간 pred가 같아지는 거리: 3.625


- 실제로 식에 값을 대입해보면 predict 결과와 똑같이 나옴
    - y_pred = w7 + b
     - y_pred = int(model_A.coef_) * 7 + int(model_A.intercept_)
     - y_pred = model.predict([[7]])